# Author: Preethi chimerla
# Team  : Rome
# This Program creates the output.xml file in senseval-2 format
# The input to this program will be initial input.xml file
# and the file generated by xmlparse.py which contains data in the format of
# {1:1 , 2:1 , 3:2, 4:1 , 5:1 , ....}
# {instance number: cluster or sense number , .... }
# Output will be in .xml in Senseval-2 format
#
# imports etree from lxml component to parse the input data
from lxml import etree

class XMLWrite(object):
    #Constructor
    def __init__(self):
        self.data=[]
    
    #takes input file path, cluster information file and writes to output file path
    def write(self,path,cluster_information,output):
        #creates parser object to recover
        parser = etree.XMLParser(recover=True)
        #reads the parsed xml
        tree=etree.parse(path,parser=parser)
        #identifies the root which is the main node
        root = tree.getroot()
        #initialising variable for further use in for loops
        value=0
        #Updates the attributes of the xml
        #Updates the sense ids of the xml based on the clusters
        for answer in root.iter('answer'):
            answer.attrib['senseid']=str(cluster_information[value])
            value=value+1
            #Updates the xml and writing it to a new xml
        tree.write(output)
